// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: kv_rwset.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVRWSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxID   string     `protobuf:"bytes,1,opt,name=TxID,proto3" json:"TxID,omitempty"`
	Reads  []*KVRead  `protobuf:"bytes,2,rep,name=Reads,proto3" json:"Reads,omitempty"`
	Writes []*KVWrite `protobuf:"bytes,3,rep,name=Writes,proto3" json:"Writes,omitempty"`
}

func (x *KVRWSet) Reset() {
	*x = KVRWSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_rwset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVRWSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVRWSet) ProtoMessage() {}

func (x *KVRWSet) ProtoReflect() protoreflect.Message {
	mi := &file_kv_rwset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVRWSet.ProtoReflect.Descriptor instead.
func (*KVRWSet) Descriptor() ([]byte, []int) {
	return file_kv_rwset_proto_rawDescGZIP(), []int{0}
}

func (x *KVRWSet) GetTxID() string {
	if x != nil {
		return x.TxID
	}
	return ""
}

func (x *KVRWSet) GetReads() []*KVRead {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *KVRWSet) GetWrites() []*KVWrite {
	if x != nil {
		return x.Writes
	}
	return nil
}

type KVRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Version *Version `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *KVRead) Reset() {
	*x = KVRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_rwset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVRead) ProtoMessage() {}

func (x *KVRead) ProtoReflect() protoreflect.Message {
	mi := &file_kv_rwset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVRead.ProtoReflect.Descriptor instead.
func (*KVRead) Descriptor() ([]byte, []int) {
	return file_kv_rwset_proto_rawDescGZIP(), []int{1}
}

func (x *KVRead) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVRead) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum uint64 `protobuf:"varint,1,opt,name=BlockNum,proto3" json:"BlockNum,omitempty"`
	GroupNum uint64 `protobuf:"varint,2,opt,name=GroupNum,proto3" json:"GroupNum,omitempty"`
	TxNum    uint64 `protobuf:"varint,3,opt,name=TxNum,proto3" json:"TxNum,omitempty"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_rwset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_kv_rwset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_kv_rwset_proto_rawDescGZIP(), []int{2}
}

func (x *Version) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *Version) GetGroupNum() uint64 {
	if x != nil {
		return x.GroupNum
	}
	return 0
}

func (x *Version) GetTxNum() uint64 {
	if x != nil {
		return x.TxNum
	}
	return 0
}

type KVWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	IsDelete bool   `protobuf:"varint,2,opt,name=IsDelete,proto3" json:"IsDelete,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *KVWrite) Reset() {
	*x = KVWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_rwset_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVWrite) ProtoMessage() {}

func (x *KVWrite) ProtoReflect() protoreflect.Message {
	mi := &file_kv_rwset_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVWrite.ProtoReflect.Descriptor instead.
func (*KVWrite) Descriptor() ([]byte, []int) {
	return file_kv_rwset_proto_rawDescGZIP(), []int{3}
}

func (x *KVWrite) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVWrite) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *KVWrite) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_kv_rwset_proto protoreflect.FileDescriptor

var file_kv_rwset_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x76, 0x5f, 0x72, 0x77, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x64, 0x0a, 0x07, 0x4b, 0x56, 0x52, 0x57, 0x53, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x78, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x78, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x56, 0x52, 0x65, 0x61, 0x64, 0x52, 0x05,
	0x52, 0x65, 0x61, 0x64, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x56, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x06, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x06, 0x4b, 0x56,
	0x52, 0x65, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x57, 0x0a,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x75, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x78, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x54, 0x78, 0x4e, 0x75, 0x6d, 0x22, 0x4d, 0x0a, 0x07, 0x4b, 0x56, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kv_rwset_proto_rawDescOnce sync.Once
	file_kv_rwset_proto_rawDescData = file_kv_rwset_proto_rawDesc
)

func file_kv_rwset_proto_rawDescGZIP() []byte {
	file_kv_rwset_proto_rawDescOnce.Do(func() {
		file_kv_rwset_proto_rawDescData = protoimpl.X.CompressGZIP(file_kv_rwset_proto_rawDescData)
	})
	return file_kv_rwset_proto_rawDescData
}

var file_kv_rwset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kv_rwset_proto_goTypes = []interface{}{
	(*KVRWSet)(nil), // 0: pb.KVRWSet
	(*KVRead)(nil),  // 1: pb.KVRead
	(*Version)(nil), // 2: pb.Version
	(*KVWrite)(nil), // 3: pb.KVWrite
}
var file_kv_rwset_proto_depIdxs = []int32{
	1, // 0: pb.KVRWSet.Reads:type_name -> pb.KVRead
	3, // 1: pb.KVRWSet.Writes:type_name -> pb.KVWrite
	2, // 2: pb.KVRead.Version:type_name -> pb.Version
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kv_rwset_proto_init() }
func file_kv_rwset_proto_init() {
	if File_kv_rwset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kv_rwset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVRWSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_rwset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_rwset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_rwset_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kv_rwset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kv_rwset_proto_goTypes,
		DependencyIndexes: file_kv_rwset_proto_depIdxs,
		MessageInfos:      file_kv_rwset_proto_msgTypes,
	}.Build()
	File_kv_rwset_proto = out.File
	file_kv_rwset_proto_rawDesc = nil
	file_kv_rwset_proto_goTypes = nil
	file_kv_rwset_proto_depIdxs = nil
}
